---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rpm
  labels:
    id: prod000017
    app: repo-rpm
    storage: cephfs
spec:
  capacity:
    storage: 512Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - 10.98.151.55:6789
      - 10.98.151.65:6789
      - 10.98.151.66:6789
    path: /rpm
    user: admin
    secretRef:
      name: ceph-admin-secret
      namespace: kube-system
    readOnly: false
  persistentVolumeReclaimPolicy: Retain